[build]
builder = "go"
buildCommand = "go build -o main ./cmd/engine"
goVersion = "1.23.3" # Specify your Go version here

[deploy]
startCommand = "./main"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[database]
type = "mongodb"